name: CI
permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Compile extension
        run: npm run compile

      - name: Install xvfb and dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgbm1 libasound2 libnspr4 libnss3 libxss1 libxtst6 libgtk-3-0 libatk-bridge2.0-0 libatspi2.0-0

      - name: Run tests on Linux (with xvfb)
        if: runner.os == 'Linux'
        run: xvfb-run -a npm test

      - name: Run tests on macOS/Windows
        if: runner.os != 'Linux'
        run: npm test

      - name: Publish to VS Code Marketplace
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
